FROM node:latest as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY ./ .
RUN npm run build

FROM nginx as production-stage
RUN mkdir /app
COPY --from=build-stage /app/dist /app
COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/time-manager-prod.conf  /etc/nginx/conf.d/time-manager-prod.conf 
RUN rm /etc/nginx/conf.d/default.conf
