version: "3"
services:
  db_prod:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
    restart: unless-stopped
    volumes:
      - 'pgdataprod:/var/lib/postgresql/data'
      - './bdd/init-deploy.sql:/docker-entrypoint-initdb.d/init.sql'

  adminer_prod:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    restart: unless-stopped
    ports:
      - "5556:80"
    depends_on:
      - db_prod
      
volumes:
  pgdataprod: