version: "3"
services:
  db_prod:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
    restart: unless-stopped
    volumes:
      - 'pgdataprod:/var/lib/postgresql/data'
      - './bdd/init-deploy.sql:/docker-entrypoint-initdb.d/init.sql'

  adminer_prod:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    restart: unless-stopped
    ports:
      - "5556:80"
    depends_on:
      - db_prod

  api_prod:
    build:
      context: "./api"
      dockerfile: Dockerfile
    image: oneflow12/test:latest_api
    env_file:
      - ./api/.env
    restart: unless-stopped
    volumes:
      - ./api:/app
    ports:
      - '4001:4001'
    depends_on:
      - db_prod
  
  client_prod:
    build:
      context: ./client
      dockerfile: Dockerfile.deploy
    image: oneflow12/test:latest_client
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - api_prod
volumes:
  pgdataprod: